//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PC_Nation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bestellung
    {
        public int BestellungsID { get; set; }
        public Nullable<System.DateTime> Bestelldatum { get; set; }
        public Nullable<int> Menge { get; set; }
        public string Preis { get; set; }
        public string Bestellstatus { get; set; }
    }
}
