//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PC_Nation
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OnlineShopDB : DbContext
    {
        public OnlineShopDB()
            : base("name=OnlineShopDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bestellung> Bestellung { get; set; }
        public virtual DbSet<Kunde> Kunde { get; set; }
        public virtual DbSet<OnlineShop> OnlineShop { get; set; }
        public virtual DbSet<Produkt> Produkt { get; set; }
        public virtual DbSet<Produktkategorie> Produktkategorie { get; set; }
        public virtual DbSet<Rückgabe> Rückgabe { get; set; }
    }
}
