//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PC_Nation
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnlineShop
    {
        public string Name { get; set; }
        public string Ort { get; set; }
        public string Postleitzahl { get; set; }
        public string Straße { get; set; }
        public string Hausnummer { get; set; }
    }
}
