//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PC_Nation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produkt
    {
        public int ProduktID { get; set; }
        public string ArtikelNummer { get; set; }
        public string ProduktName { get; set; }
        public string Beschreibung { get; set; }
        public string Preis { get; set; }
        public string Bild { get; set; }
        public Nullable<int> KategorieID { get; set; }
    
        public virtual Produktkategorie Produktkategorie { get; set; }
    }
}
