//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PC_Nation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rückgabe
    {
        public string Email { get; set; }
        public string Rechnungsnummer { get; set; }
        public string Artikelnummer { get; set; }
        public string Kommentar { get; set; }
    }
}
